apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-run
  name: my-final-run
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "quay.io/wpernath/kustomize-ubi:v4.4.1"              
          command: 
          - /bin/sh
          - -c 
          - |
            echo "WELCOME TO the post installation hook for ArgoCD "
            echo "-------------------------------------------------"
            echo "We are now going to fill the database by calling "
            echo "the corresponding REST service"
            
            NUM_PERSONS=$(curl http://person-service.book-dev.svc:8080/person/count)

            if [ $NUM_PERSONS -eq 0 ]; then
              echo "There are no persons in the database, filling some"
               
              http --ignore-stdin --json POST person-service.book-dev.svc:8080/person firstName=Carlos lastName=Santana salutation=Mr
              http --ignore-stdin --json POST person-service.book-dev.svc:8080/person firstName=Joe lastName=Cocker salutation=Mr
              http --ignore-stdin --json POST person-service.book-dev.svc:8080/person firstName=Eric lastName=Clapton salutation=Mr
              http --ignore-stdin --json POST person-service.book-dev.svc:8080/person firstName=Kurt lastName=Cobain salutation=Mr

            fi
            