apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

#namePrefix: dev-
commonLabels:
  variant: development


# replace the image tag of the container with latest
images:
- digest: sha256:f6f4d1fba645f4e01f1bf527d7dbcf8abc164b3cb8f1de65cca1519e9cbe4cd6
  name: quay.io/wpernath/person-service:latest
  newName: quay.io/wpernath/person-service:latest

# generate a configmap 
configMapGenerator:
- literals:
  - APP_GREETING=We are in DEVELOPMENT mode
  name: app-config
      
# this patch needs to be done, because kustomize does not change 
# the route target service name
#patches:
#- patch: |-
#    - op: replace
#      path: /spec/to/name
#      value: dev-person-service
# target:
#   kind: Route
